# Generated by Django 3.1.5 on 2021-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(default='test interests', max_length=200),
        ),
    ]
