# Generated by Django 3.1.5 on 2021-01-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210122_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_email',
            new_name='user',
        ),
    ]
