# Generated by Django 3.1.5 on 2021-01-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        ('workshops', '0002_auto_20210120_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='expert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='experts.expert'),
        ),
    ]
