# Generated by Django 3.1.5 on 2021-01-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('facbook_link', models.CharField(default='www.facebook.com', max_length=200)),
                ('twitter_link', models.CharField(default='www.twitter.com', max_length=200)),
            ],
        ),
    ]
